schema_version: 1

context:
  version: "4.15.4"

recipe:
  name: z3prover
  version: ${{ version }}

source:
  url: https://github.com/Z3Prover/z3/archive/refs/tags/z3-${{ version }}.tar.gz
  sha256: dae526252cb0585c8c863292ebec84cace4901a014b190a73f14087dd08d252b
  patches:
    # backport https://github.com/Z3Prover/z3/pull/8088
    - patches/0001-BLD-Add-CMake-option-to-build-Python-bindings-withou.patch

build:
  number: 1
  skip: win

outputs:
  - package:
      name: libz3
    build:
      script:
        - build_lib
    requirements:
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - if: linux
          then: libgomp
        - if: osx
          then: llvm-openmp
      host:
        - python *
        - if: linux
          then: libgomp
        - if: osx
          then: llvm-openmp
      ignore_run_exports:
        from_package:
          - python
      run_exports:
        - ${{ pin_subpackage("libz3", upper_bound='x') }}
      run_constraints:
        - z3prover ==${{ version }}

    tests:
      - package_contents:
          lib:
            - z3
          files:
            # versioned libraries
            - if: linux
              then:
                - lib/libz3.so.${{ version }}*
            - if: osx
              then:
                - lib/libz3.${{ version }}*.dylib
            # binaries
            - bin/z3
            # headers
            - include/z3_algebraic.h
            - include/z3_api.h
            - include/z3_ast_containers.h
            - include/z3_fixedpoint.h
            - include/z3_fpa.h
            - include/z3.h
            - include/z3++.h
            - include/z3_macros.h
            - include/z3_optimization.h
            - include/z3_polynomial.h
            - include/z3_rcf.h
            - include/z3_v1.h
            - include/z3_spacer.h
            - include/z3_version.h
            # cmake & pkgconfig metadata
            - lib/cmake/z3/Z3Targets.cmake
            - lib/cmake/z3/Z3Targets-release.cmake
            - lib/cmake/z3/Z3Config.cmake
            - lib/cmake/z3/Z3ConfigVersion.cmake
            - lib/pkgconfig/z3.pc
      - script:
          - z3 --help

  - package:
      name: z3-solver
    build:
      script:
        - build_py
    requirements:
      build:
        - if: build_platform != host_platform
          then:
            - cross-python_${{ host_platform }}
        # even for native builds, so we can uniformly use
        # -DPython3_EXECUTABLE=${BUILD_PREFIX}/bin/python in build_py.sh
        - python
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - ninja
        - if: linux
          then: libgomp
        - if: osx
          then: llvm-openmp
      host:
        - ${{ pin_subpackage("libz3", exact=True) }}
        - python
        - setuptools
        - pip
        - if: linux
          then: libgomp
        - if: osx
          then: llvm-openmp
      run:
        - ${{ pin_subpackage("libz3", exact=True) }}
        - python

    tests:
      - python:
          imports:
            - z3
          pip_check: true

  - package:
      # compatibility for previous name of library
      name: z3prover
    requirements:
      host:
        - ${{ pin_subpackage("libz3", exact=True) }}
      run:
        - ${{ pin_subpackage("libz3", exact=True) }}
      run_exports:
        - ${{ pin_subpackage("libz3", upper_bound='x') }}
    tests:
      - script:
          - z3 --help

about:
  license: MIT
  license_file: LICENSE.txt
  summary: The Z3 Theorem Prover
  homepage: https://github.com/Z3Prover/z3
  repository: https://github.com/Z3Prover/z3
  documentation: https://github.com/Z3Prover/z3/wiki#background

extra:
  recipe-maintainers:
    - martin-g
    - h-vetinari
