schema_version: 1

context:
  name: z3prover
  version: 4.13.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Z3Prover/z3/archive/refs/tags/z3-${{ version }}.tar.gz
  sha256: 4071977e66e9f3d239b7b098ceddfe62ffdf3c71e345e9524a4a5001d1f4adf3

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
  host:
    - python
    - if: linux
      then: libgomp
    - if: osx
      then: llvm-openmp
  run:
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x') }}
  
tests:
  - script:
      - if: linux
        then: test -f ${PREFIX}/lib/libz3${SHLIB_EXT}.${{ version }}*
      - if: osx
        then: test -f ${PREFIX}/lib/libz3.${{ version }}*${SHLIB_EXT}
      - test -f ${PREFIX}/lib/libz3${SHLIB_EXT}
      - test -f ${PREFIX}/include/z3_algebraic.h
      - test -f ${PREFIX}/include/z3_api.h
      - test -f ${PREFIX}/include/z3_ast_containers.h
      - test -f ${PREFIX}/include/z3_fixedpoint.h
      - test -f ${PREFIX}/include/z3_fpa.h
      - test -f ${PREFIX}/include/z3.h
      - test -f ${PREFIX}/include/z3++.h
      - test -f ${PREFIX}/include/z3_macros.h
      - test -f ${PREFIX}/include/z3_optimization.h
      - test -f ${PREFIX}/include/z3_polynomial.h
      - test -f ${PREFIX}/include/z3_rcf.h
      - test -f ${PREFIX}/include/z3_v1.h
      - test -f ${PREFIX}/include/z3_spacer.h
      - test -f ${PREFIX}/include/z3_version.h
      - test -x ${PREFIX}/bin/z3
      - test -f ${PREFIX}/lib/cmake/z3/Z3Targets.cmake
      - test -f ${PREFIX}/lib/cmake/z3/Z3Targets-release.cmake
      - test -f ${PREFIX}/lib/cmake/z3/Z3Config.cmake
      - test -f ${PREFIX}/lib/cmake/z3/Z3ConfigVersion.cmake
      - test -f ${PREFIX}/lib/pkgconfig/z3.pc
      - z3 --help

about:
  license: MIT
  license_file: LICENSE.txt
  summary: The Z3 Theorem Prover
  homepage: https://github.com/Z3Prover/z3
  repository: https://github.com/Z3Prover/z3
  documentation: https://github.com/Z3Prover/z3/wiki#background

extra:
  recipe-maintainers:
    - martin-g
